### ISSUE TITLE
Chrome sometimes aligns images from the vertical middle downwards

### ISSUE THREAD

**Issue by keimpema** [buildinternet/supersized#28]
edit: using Chrome 12.0.742.122 for windows (latest version)

As mentioned before on the supersized blog by John B and myself Chrome sometimes aligns images from the vertical middle downwards. It must have something to do with Chrome not having the image details available at the same time as other browsers (see also http://stackoverflow.com/questions/318630/get-real-image-width-and-height-with-javascript-in-safari-chrome).

In

// Vertically Center
if (base.options.vertical_center){
$(this).css(‘top’, (browserheight – $(this).height())/2);
}

$(this).height() sometimes is 0 in Chrome.

Moving the initialization from $(document).ready to $(window).load does not make a difference. Most likely because the images are loaded dynamically.

Resizing the browser corrects the problem and the image is vertically centered nicely.

See example @ http://vankeimpema.net/test.

Harmen

**Comment by keimpema** [comment]
I believe the problem is solved by adding thumbmail images! Must have something to do with the images already being cached when used as thumbnails as well.

**Comment by notarocketscientist** [comment]
Hi!

First of all: awesome plugin...but that Chrome Bug makes me mad. As keimpema said, sometimes the browser-height is 0.
I put in an alert and kept surfing my website. (I'm running Win7 / Chrome 13.0.782xxx.) How can this be?

I'm using the supersized-core-version (not the slideshow), so adding thumbnails are not my solution... (?)
Chrome gets more and more widespread these days, we all know...so I would kindly ask for a fix of this issue.

I have only limited JS skills, but could it be an approach to gather the browser dimensions "on load" instead of resizeNow()?
Or maybe gather them once first and then overwrite them when the browser gets resized?
I never had this bug after manually resizing. The occur when I simply browse my website - and while the browser window (size) remains untouched...

Best regards!

**Comment by colbyfayock** [comment]
having this issue as well and like notarocketscientist, won't be using thumbs
http://www.colbyfayock.com/endagraph

works great besides that

**Comment by proov** [comment]
same problem.. this bug occur on the LAST slide.. often i have the top at ~500px so the image is beggening from the vertical center... Mac OSX.6.8 on Chrome 14.0.835.186

**Comment by pixelmachine** [comment]
Ok easiest fix i've found for this is to use the [imagesloaded plugin](https://github.com/desandro/imagesloaded) along side supersized and just replace all .load() events with .imagesLoaded()

This way the images are always loaded correctly and you never see incorrectly centred images.

**Comment by proov** [comment]
i guess this is fixed with Chrome15...

**Comment by pixelmachine** [comment]
It still happens in Safari, I haven't tested Chrome 15. load() is notoriously unreliable as a method to determine if an image is completely loaded which is the reason the imagesloaded exists.

The other problem is that you may find the problem is inconsistent. If you hit an unusually slow connection you'll likely find the problem reoccurs. I had at least two weeks of not seeing anything before it came back worse than ever.

**Comment by ryan-jagger** [comment]
I also have this issue. I am not using thumbnails. This only occurs for me on the next to last slide listed under 'slides'.

**Comment by notarocketscientist** [comment]
As long as there's no statement for this issue here from the supersized developer, I'd like to say that meanwhile I switched to Vegas (http://vegas.jaysalvat.com/).

Vegas works fine for me now, allthough I had problems with that one, too. Fortunately I could find a workaround. Have a look here, if you encounter squeezed images. https://github.com/jaysalvat/vegas/issues/8

The above announcement is not meant as a hostile takeover. I deeply respect the work of all plugin-creators, especially when there "product" is good (like supersized). I'm just trying to help the people whit this issue.

By the way: vegas.js also uses the imagesLoaded-Plugin which suburbiaboy meantioned above. Maybe this could really be the solution.

**Comment by pdikmann** [comment]
+1 on this issue on Safari 5.1.2 on Mac Os X 10.6.8

The [fix](https://github.com/buildinternet/supersized/issues/28#issuecomment-2578514) proposed by @suburbiaboy works fine here.

**Comment by LetterAfterZ** [comment]
+1 to this issue in Win7 on both Chrome and Firefox for me.

Took me a couple hours to pinpoint the exact cause of the issue. Going to try that imagesloading fix.

**Comment by LetterAfterZ** [comment]
Can't seem to work out how to make this work with ImagesLoaded. If anyone has any clearer instrcutions that would be great. 

When trying to replace load() with imagesLoaded() I get this error:

Uncaught TypeError: Cannot use 'in' operator to search for 'width' in undefined
